 
  
# Iteration 9 Incircle Yaml
  lbl_home_incircle: "INCIRCLE"
  incl_home_popup_addcard: "ADD CARD"
  incl_home_popup_nothanks: "NO THANKS"
  incl_scr_viewfullsite: "circleFourViewFullSiteButton"
  incl_scr_circletabone: "circleOneButton"
  lbl_home_incl_pgm_tutorial: "F0.jhtml"
  lbl_incl_tab_iphone: "CIRCLE ONE"
  lbl_iphone_view_full_site: "iPhCircleOneViewFullSite"
  incl_gift_perk_card: "circleOnePerkSubTitle"
  incl_gift/perk_card: "incirleperkcardimage"
  incl_perk_detail_copy: "COPY"
  incl_perk_copy_value: "LOYALTY GIFT CARD"
  incl_perk_detail_done: "DONE"
  
            # Iteration 9- NAD 
  hom_incrle_btn: "INCIRCLE"
  incrle_popup: "ACCESS THE ACCOUNT PAGE TO ADD YOUR CARD"
  incle_popup_add_crd_btn: "ADD CARD"
  incle_popup_no_thnk_btn: "NO THANKS"
  incrle_mnu_circl_one: "circleOneButton"
  incrle_mnu_circl_two: "circleTwoButton"
  incrle_mnu_circl_thr: "circleThreeButton"
  incrle_mnu_circl_for: "circleFourButton"
  incrle_mnu_prsdnt_crl: "presidentCircleButton"
  incrle_vew_ful_sit_btn: "presidentViewFullSiteButton"
          # Iteration 9- Fazil
  Add_card_btn: "add card"
  hom_incrle_btn: "INCIRCLE"
  incrle_popup: "ACCESS THE ACCOUNT PAGE TO ADD YOUR CARD"
  incle_popup_add_crd_btn: "ADD CARD"
  incle_popup_no_thnk_btn: "NO THANKS"
  card_tittle: ""
  incrle_mnu_circl_one: "circleOneButton"
  incrle_mnu_circl_two: "circleTwoButton"
  incrle_mnu_circl_thr: "circleThreeButton"
  incrle_mnu_circl_for: "circleFourButton"
  incrle_mnu_prsdnt_crl: "presidentCircleButton"
  incrle_vew_ful_sit_btn: "presidentViewFullSiteButton"
  Earned_gifts: "signInAvailablePoints"
  learn_more: "learnmore"
  view_fullsite: "viewfullsite"
  validate_url: "Address"
  incl_view_full_site_ipad: "circleOneViewFullSiteButton"
  incl_perk_card_img: "CARD VALUE - $550.00"
  incl_perk_popup_back: "productListViewControllerBack"
  incl_perk_iphone_copy: "iPhGiftCardCopyButton"
  incl_perk_clipboard_iphone: "iPhGiftCardLoyalityTitle"
  incl_scr_title_ipad: "signInPresidentTitle"
  incl_scr_learn_ipad: "signInLearnMoreButton"
  incl_scr_earned_ipad: "signInEarnedCards"
  incl_circle_level_info: "signInGiftCardPointsAway"
  incl_circle_view_full: "presidentViewFullSiteButton"
  incl_circle_title_iphone: "iPhSignInTitle"
  incl_circle_learn_iphone: "iPhSignInLearnMoreButton"
  incl_cir_earned_iphone: "iPhSignInEarnedTotalLabel"
  incl_cir_pointaway_iphone: "iPhSignInAllPointsLabel"
  incl_cir_learn_iphone: "iPhSignInLearnMoreButton"
  incl_learn_page_iphone: "iPhCirclePresidentTitle"
  incl_iphone_viewfull_learn: "iPhCirclePresidentViewFullSite"
  incl_learn_table_iphone: "iPhSignInEarnedTotalLabel"
  incl_learn_table_iph1: "iPhSignInRedeemedTotalLabel"
  incl_learn_table_iph2: "iPhSignInAvailablePointsLabel"
  incl_learn_table_iph3: "iPhSignInGiftCardAwayPoints"
  incl_screen_view_full: "iPhSignInViewFullSite"
  